services:
  # Frontend Service
  - type: web
    name: kltn-fe-ecom
    env: docker
    dockerContext: ./kltn-fe-ecom
    dockerfilePath: ./kltn-fe-ecom/Dockerfile
    plan: free
    envVars:
      - key: NEXT_PUBLIC_API_URL
        sync: false
      - key: NEXT_PUBLIC_CHATBOT_URL
        sync: false

  # Backend Service
  - type: web
    name: be-api-service
    env: docker
    dockerContext: ./BE
    dockerfilePath: ./BE/Dockerfile
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-queue
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: MOMO_PARTNER_CODE
        sync: false
      - key: MOMO_ACCESS_KEY
        sync: false
      - key: MOMO_SECRET_KEY
        sync: false
      - key: MOMO_IPN_URL
        sync: false
      - key: VNPAY_TMN_CODE
        sync: false
      - key: VNPAY_HASH_SECRET
        sync: false
      - key: VNPAY_RETURN_URL
        sync: false
      - key: VNPAY_FRONTEND_RETURN_URL
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false

  # Chatbot Service
  - type: web
    name: chatbot-service
    env: docker
    dockerContext: ./chatbot-kltn
    dockerfilePath: ./chatbot-kltn/Dockerfile
    plan: free
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis-queue
          property: connectionString

  # Redis (Free Managed)
  - type: redis
    name: redis-queue
    plan: free
    ipAllowList: []
